import { component$, useSignal, useVisibleTask$ } from "@builder.io/qwik";

const LEGAL_TEXT = [
  "© 2026 SLOP.ZONE — All rights reserved (probably)",
  "Powered by AI™, Blockchain™, and Vibes™",
  "No actual AIs were consulted in the making of this website",
  "Terms of Service: There are no terms. Do whatever.",
  "Privacy Policy: We don't collect data because we don't know how",
  "Cookie Policy: 🍪🍪🍪 That's it. That's the policy.",
  "This footer was generated by an AI that doesn't exist",
  "Synergy score: ∞ | Disruption level: YES",
  "If you read this far, you are now legally a slop enthusiast",
];

export default component$(() => {
  const text = useSignal("");

  useVisibleTask$(() => {
    text.value = `${LEGAL_TEXT.join(" • ")} • `;
  });

  return (
    <footer class="mt-auto border-t border-white/10 bg-slop-bg/80 backdrop-blur-xl">
      <div class="overflow-hidden py-3">
        <div class="animate-marquee whitespace-nowrap text-xs text-white/30 font-mono">
          {text.value}
          {text.value}
        </div>
      </div>
      <div class="max-w-7xl mx-auto px-4 py-6 flex flex-col sm:flex-row items-center justify-between gap-4">
        <p class="comic-title text-sm text-white/50">
          Powered by <span class="text-slop-purple">AI™</span> and <span class="text-slop-cyan">bad decisions™</span>
        </p>
        <p class="text-xs text-white/30 font-mono">built with qwik + motion + gsap + vibes</p>
      </div>
    </footer>
  );
});
